### ISSUE TITLE
archlinux下编译失败

### ISSUE THREAD

**Issue by U2FsdGVkX1** [artificerpi/MT7603U#1]
```
make -C tools
make[1]: 进入目录“/home/u2fsdgvkx1/桌面/MT7603U/tools”
gcc -g bin2h.c -o bin2h
make[1]: 离开目录“/home/u2fsdgvkx1/桌面/MT7603U/tools”
/home/u2fsdgvkx1/桌面/MT7603U/tools/bin2h
chipset = mt7603u
cp -f os/linux/Makefile.6 /home/u2fsdgvkx1/桌面/MT7603U/os/linux/Makefile
make -C /lib/modules/4.10.2-1-ARCH/build SUBDIRS=/home/u2fsdgvkx1/桌面/MT7603U/os/linux modules
make[1]: 进入目录“/usr/lib/modules/4.10.2-1-ARCH/build”
make[1]: *** 没有规则可制作目标“modules”。 停止。
make[1]: 离开目录“/usr/lib/modules/4.10.2-1-ARCH/build”
make: *** [Makefile:172：LINUX] 错误 2
```

系统为archlinux
```Linux localhost.localdomain 4.10.2-1-ARCH #1 SMP PREEMPT Mon Mar 13 17:13:41 CET 2017 x86_64 GNU/Linux```

360随身WiFi三代（MT7603U）

由于不是很懂Makefile语法，所以只好来发一个issue了……

先谢谢一下

**Comment by artificerpi** [comment]
注意这两行
``` 
make[1]: 进入目录“/usr/lib/modules/4.10.2-1-ARCH/build”
make[1]: *** 没有规则可制作目标“modules”。 停止。
```
@U2FsdGVkX1 你需要下载好对应的系统内核源码，然后再编译内核。顺便一提，这份代码还没有测试通过，如果你想测试和修改，请获取master分支的代码， 因为master分支的代码只是稍微修改了一下官方的代码，但是依然有很多bug。 develop分支目前只支持在ubuntu上测试。

**Comment by U2FsdGVkX1** [comment]
已安装成功，但不能使用。。。
不过我分析了一下源码，好像源码内的7603U硬件ID被定义为0e8d:7603，而我的360随身WiFi三代同为7603U芯片，但是硬件ID为0e8d:760c，同时我搜索了一下，还有一个人的360随身WiFi三代的硬件ID为0e8d:760c
所以想请问一下，你是不是360随身WiFi三代在ubuntu下测试的呢？

**Comment by artificerpi** [comment]
我的确使用360随身WIFI测试。但是那个旧的源码使用linux 2.6内核编译，目前放上来的代码还有许多问题，并不能使用，希望大家能一起改进
